spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:${REDIS_URL:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}}
      ssl:
        enabled: ${REDIS_SSL:false}
  flyway:
    enabled: true
    default-schema: loadix
    schemas: loadix
    create-schemas: true

loadix:
  security:
    cookie-secure: false

logging:
  level:
    root: WARN
    com.loadix: INFO
